#8001表示注册到zookeeper服务器的服务提供者端口号
server:
  port: 3344

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: student-config
  cloud:
    zookeeper:
      connect-string: 120.53.225.156:2181

    config:
      server:
        git:
          uri: https://gitee.com/jiao_qianjin/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: dev
