server:
  port: 8769
spring:
  application:
    name: student-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务注册中心地址
        namespace: e672b2a4-c0f0-4752-931f-9f8101d533bb
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
